language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

os:
  - linux
  - osx

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

  matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true