language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - ./update

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true